on:
  push:
    tags:
      - "v*"
name: Upload Binaries to Release
jobs:
    build:
        permissions: write-all
        name: Upload Binaries to Release
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: "Setup Python Environment"
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.12'
                cache: 'pip'
            - run: pip install xonsh

            - name: Setup MinGW Compiler
              uses: egor-tensin/setup-mingw@v2
              with:
                platform: x64

            - name: Install ARM32 GNU Compiler
              run: sudo apt install gcc-arm-linux-gnueabi -y

            - name: Install ARM64 GNU Compiler
              run: sudo apt install gcc-aarch64-linux-gnu -y

            - name: Setup Android NDK
              id: setup-ndk
              uses: nttld/setup-ndk@v1
              with:
                ndk-version: r28-beta2

            - name: Setup Lua Runtime
              run: sudo apt install lua5.1 -y

            - name: Generate Release Notes
              env:
                  CG_CONFIG_URL: "https://gist.githubusercontent.com/eeriemyxi/da2edd0187f157f3de1f2dc74bdb6426/raw/6dc75529abb9ce54b5dc3ed2cc83afbb55691443/cliff.toml"
                  CG_REPO_URL: ${{github.server_url}}/${{github.repository}}
              run: |
                  pip install git-cliff
                  curl -s "$CG_CONFIG_URL" | python -c "import sys,os;lines=sys.stdin.read();print(lines.replace('{{REPO}}',os.environ['CG_REPO_URL']))" > cliff.toml
                  git-cliff -l -o RELEASE-NOTES.md
                  echo "RELEASE-NOTES.md:\n"
                  cat RELEASE-NOTES.md

            - name: Build Binaries
              run: |
                export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
                chmod +x build.xsh && xonsh build.xsh
              env:
                ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

            - name: Upload Binaries to Release
              uses: softprops/action-gh-release@v2
              with:
                  body_path: RELEASE-NOTES.md
                  files: |
                      build/linux/bin/*.bin
                      build/linux-arm32/bin/*.bin
                      build/linux-arm64/bin/*.bin
                      build/linux-android-arm64/bin/*.bin
                      build/windows/bin/*.exe
